title: "Jude Chryst Degilles POUMINA"
logo: img/nny.jpg
description: "Portfolio Master ERIS"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr

# ğŸ“‚ Collections personnalisÃ©es
collections:
  projects:
    output: true
    permalink: /projects/:name
  experiences:
    output: true
    permalink: /experiences/:name

    # ğŸ§­ Menu de navigation (liens en haut du portfolio)
nav:
  - title: "ğŸ  Accueil"
    url: /
  - title: "ğŸ’¼ Projets"
    url: /projects
  - title: "ğŸ§° ExpÃ©riences"
    url: /experiences
  - title: "ğŸ“š Formation"
    url: /education
  - title: "ğŸ“« Contact"
    url: /contact
